### ISSUE TITLE
long input - larger than 510 tokens

### ISSUE THREAD

**Issue by DiddyC** [NormXU/ERNIE-Layout-Pytorch#17]
Hi,

Does anyone have experience with running the model when there's more than 510 tokens?
Is the best way to chunk the text and then run it twice with the same questions (perhaps with a stride)?

Also, any idea how to run it with multiple questions at once?

**Comment by NormXU** [comment]
Hi DiddyC,

Here are some ideas to increase the sequence length, which may be helpful for tasks that require longer input sequences

## Some ideas
1. Let's say, we want to increase the max sequence length to 1024, twice of the original pre-trained sequence length.  Simply duplicate the position embedding values from the range of 0-511 to the range of 512-1023, and the second set of 512 position embeddings will utilize the same weight values as the first set of 512 position embeddings.
2. Use [RoPE](https://huggingface.co/docs/transformers/model_doc/roformer)
3. window slide；
As the image shows below, since our training sequence length is 7, we can shift the available sequence by a predicted length of 9, as shown in this image.
![slide attention](https://user-images.githubusercontent.com/33339685/231232507-b317b1aa-5324-4361-9a0f-c2b16e9e697b.png)

Hope these ideas can help

**Comment by NormXU** [comment]
hope this commit can help
