### ISSUE TITLE
Ernie-Layout english weights?

### ISSUE THREAD

**Issue by logan-markewich** [NormXU/ERNIE-Layout-Pytorch#7]
Is there actually an english version of ernie layout? I only see `PaddlePaddle/ernie-layoutx-base-uncased` on huggingface, which is the normal cross-lingual version.

That's fine too though! I will try out the cross-lingual version in the meantime :) Thanks for providing this work!

**Comment by NormXU** [comment]
Oh, my bad. The readme file I wrote is a little confusing. 

Actually, the [Pytorch-style ERNIE-Layout Pretrained Model](https://huggingface.co/Norm/ERNIE-Layout-Pytorch/tree/main) is translated from [PaddlePaddle/ernie-layoutx-base-uncased](https://huggingface.co/PaddlePaddle/ernie-layoutx-base-uncased). 


Paddle officially released an English version model but only in inference/static mode. 

You can run 

```
from paddlenlp import Taskflow
Taskflow("document_intelligence", lang="en")
```
to see two inference models saved under `/root/.paddlenlp/taskflow/document_intelligence/docprompt/static`. One is "infer_model.pdmodel" and its parameters were saved in " infer_model.pdiparams". You can try to convert these inference models into a torch version, but I have to say this is quite challenging due to the lack of documentation.

**Comment by logan-markewich** [comment]
wow, they sure didn't make that easy haha.

I'll see how the version you've worked on goes for my use-case. If I end up reverse engineering those params I'll share the model here 👍🏻
